# Generated by Django 6.0.1 on 2026-01-13 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_adjustments', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualadjustment',
            name='statement',
        ),
        migrations.AddField(
            model_name='manualadjustment',
            name='result',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manual_adjustments', to='results.processingresult'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manualadjustment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manualadjustment',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manualadjustment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
