# Generated by Django 6.0.1 on 2026-01-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_processingjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='privacy_mode',
            field=models.CharField(choices=[('TEMPORARY', 'Temporary'), ('PERSIST', 'Persist')], default='TEMPORARY', max_length=20),
        ),
    ]
